const router = require('koa-router')()

const enumController = require('./enum')
const courseController = require('./course')
const leaveAreaController = require('./leaveArea')
const spaceAreaController = require('./spaceArea')
const spaceRuleController = require('./spaceRule')
const studentController = require('./student')
const teacherController = require('./teacher')

router.post('/api/enums', enumController.create.bind(enumController))
router.delete('/api/enums/:id', enumController.destroy.bind(enumController))
router.put('/api/enums/:id', enumController.update.bind(enumController))
router.get('/api/enums/:id', enumController.show.bind(enumController))
router.get('/api/enums', enumController.index.bind(enumController))

router.post('/api/courses', courseController.create.bind(courseController))
router.delete('/api/courses/:id', courseController.destroy.bind(courseController))
router.put('/api/courses/:id', courseController.update.bind(courseController))
router.get('/api/courses/:id', courseController.show.bind(courseController))
router.get('/api/courses', courseController.index.bind(courseController))

router.post('/api/leaveAreas', leaveAreaController.create.bind(leaveAreaController))
router.delete('/api/leaveAreas/:id', leaveAreaController.destroy.bind(leaveAreaController))
router.put('/api/leaveAreas/:id', leaveAreaController.update.bind(leaveAreaController))
router.get('/api/leaveAreas/:id', leaveAreaController.show.bind(leaveAreaController))
router.get('/api/leaveAreas', leaveAreaController.index.bind(leaveAreaController))

router.post('/api/spaceAreas', spaceAreaController.create.bind(spaceAreaController))
router.delete('/api/spaceAreas/:id', spaceAreaController.destroy.bind(spaceAreaController))
router.put('/api/spaceAreas/:id', spaceAreaController.update.bind(spaceAreaController))
router.get('/api/spaceAreas/:id', spaceAreaController.show.bind(spaceAreaController))
router.get('/api/spaceAreas', spaceAreaController.index.bind(spaceAreaController))

router.post('/api/spaceRule', spaceRuleController.create.bind(spaceRuleController))
router.delete('/api/spaceRule/:id', spaceRuleController.destroy.bind(spaceRuleController))
router.put('/api/spaceRule/:id', spaceRuleController.update.bind(spaceRuleController))
router.get('/api/spaceRule/:id', spaceRuleController.show.bind(spaceRuleController))
router.get('/api/spaceRule', spaceRuleController.index.bind(spaceRuleController))

router.post('/api/students', studentController.create.bind(studentController))
router.delete('/api/students/:id', studentController.destroy.bind(studentController))
router.put('/api/students/:id', studentController.update.bind(studentController))
router.get('/api/students/:id', studentController.show.bind(studentController))
router.get('/api/students', studentController.index.bind(studentController))

router.post('/api/teachers', teacherController.create.bind(teacherController))
router.delete('/api/teachers/:id', teacherController.destroy.bind(teacherController))
router.put('/api/teachers/:id', teacherController.update.bind(teacherController))
router.get('/api/teachers/:id', teacherController.show.bind(teacherController))
router.get('/api/teachers', teacherController.index.bind(teacherController))

module.exports = router.routes()